apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=azure
        - --email-domain=*
        - --https-address=0.0.0.0:8443
        # AzureAD callback response cookie exceeds 4KB limit
        - --session-cookie-minimal
        - --cookie-expire=20h
        env:
        ##############################################
        # OAUTH2-PROVIDER-CONFIG
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-azuread-secret
              key: client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-azuread-secret
              key: client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-azuread-secret
              key: cookie_secret
        - name: OAUTH2_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: oauth2-azuread-secret
              key: oidc_issuer_url
        - name: OAUTH2_PROXY_COOKIE_DOMAINS
          valueFrom:
            secretKeyRef:
              name: oauth2-azuread-secret
              key: cookie_domain
        - name: OAUTH2_PROXY_WHITELIST_DOMAINS
          valueFrom:
            secretKeyRef:
              name: oauth2-azuread-secret
              key: cookie_domain
        ##############################################
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 8443
          protocol: TCP
